name: Basic Test
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Compile
        run: sh build.sh
      - name: Run tests
        run: sh test.sh
